version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      PAPER_DOWNLOAD_URL: "https://api.papermc.io/v2/projects/paper/versions/1.18.2/builds/387/downloads/paper-1.18.2-387.jar"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./config:/data:z
      - ./plugins:/data/plugins:z
